{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.phuongtran",
    "module": "logcat-engine-core",
    "version": "1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.5"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-engine-core-1.3.aar",
          "url": "logcat-engine-core-1.3.aar",
          "size": 2103521,
          "sha512": "880085a1316db42b5f07356ec7fb76a9abb6b02f645e7192b2ee877df7b2e31d867dce506f7f29e1a1467aeab381b55c8084eb2219d415d60c86fba9ca46cdd6",
          "sha256": "c715e94beeb512e05ac7fc7ed83a85d943029b01641ea1d08dd6295e87d2b1b4",
          "sha1": "8d10c3f8afdd53a6a7767d74ef145ab591e1e154",
          "md5": "c9c224054e0038cf792340a8e56d0936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "logcat-engine-core-1.3.aar",
          "url": "logcat-engine-core-1.3.aar",
          "size": 2103521,
          "sha512": "880085a1316db42b5f07356ec7fb76a9abb6b02f645e7192b2ee877df7b2e31d867dce506f7f29e1a1467aeab381b55c8084eb2219d415d60c86fba9ca46cdd6",
          "sha256": "c715e94beeb512e05ac7fc7ed83a85d943029b01641ea1d08dd6295e87d2b1b4",
          "sha1": "8d10c3f8afdd53a6a7767d74ef145ab591e1e154",
          "md5": "c9c224054e0038cf792340a8e56d0936"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "logcat-engine-core-1.3-sources.jar",
          "url": "logcat-engine-core-1.3-sources.jar",
          "size": 18259,
          "sha512": "dcb17e6895cfffd2321df1ea24b11d400a9f94f71bd3b948c55768c1a3e1348be55d992124e2c387690893596ed86535efbc6b6c803e0f520843df4645ff160e",
          "sha256": "742fcbadeb717dcccf74130813f0bca6c56be00cb11c52ae1d0b783eb3c39403",
          "sha1": "698392898f987208d35b715a72ba3b92eb36d6bf",
          "md5": "55799e5d271d6b8cc9535bbbd6d6bc2e"
        }
      ]
    }
  ]
}
